name = "turkish-lexicon-worker"
main = "src/index.ts"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

[vars]
API_BASE_PATH = "/api"

[[d1_databases]]
binding = "DB"
database_name = "turkish_lexicon"
database_id = "${TURKISH_LEXICON_DB_ID}"
